<?php
 require_once('Database.php');
 require_once('Page.php');
 require_once('Banner.php');
 require_once('Quote.php');
 require_once('Portfolio.php');
 require_once('Qna.php');
 require_once('Contact.php');
 require_once('Menu.php');
 require_once('User.php'); 
?>